# Generated by Django 3.1 on 2020-08-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Operator Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('institution', models.CharField(max_length=50, verbose_name='Institution')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('status_start', models.DateTimeField(verbose_name='DateTime status begins')),
                ('status_end', models.DateTimeField(blank=True, null=True, verbose_name='DateTime status ends')),
                ('last_updated', models.DateTimeField(verbose_name='DateTime of last update')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Installation Name')),
                ('type', models.CharField(blank=True, choices=[('Dome', 'Dome'), ('Dish', 'Dish'), ('Enclosure', 'Enclosure'), ('Array', 'Array'), ('Spacecraft', 'Spacecraft')], default='Dome', max_length=30, null=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCapabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=50, verbose_name='Description of capability')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Operator Name')),
                ('location', models.CharField(blank=True, choices=[('Ground-based', 'Ground-based'), ('Space', 'Space')], default='Ground-based', max_length=30, null=True, verbose_name='Location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Latitude (N) in decimal degrees')),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Longitude (E) in decimal degrees')),
                ('altitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Altitude (m)')),
                ('orbit', models.CharField(blank=True, choices=[('Earth orbit', 'Earth orbit'), ('L2', 'L2'), ('Earth-trailing', 'Earth-trailing'), ('Mars orbit', 'Mars orbit'), ('Outbound trajectory', 'Outbound trajectory')], max_length=30, null=True, verbose_name='Orbit')),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Telescope Name')),
                ('aperture', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Telescope Effective Aperture (m)')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oss.installation')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oss.facilityoperator')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oss.site')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Instrument Name')),
                ('wavelength', models.CharField(blank=True, choices=[('Optical', 'Optical'), ('IR', 'Infrared'), ('Microwave', 'Microwave'), ('Radio', 'Radio'), ('UV', 'UV'), ('Gamma ray', 'Gamma ray'), ('X-ray', 'X-ray'), ('Gravitational waves', 'Gravitational waves'), ('Neutrinos', 'Neutrinos')], default='Optical', max_length=30, null=True, verbose_name='Wavelength range/messenger')),
                ('capabilities', models.ManyToManyField(blank=True, null=True, to='oss.InstrumentCapabilities')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oss.site'),
        ),
    ]
