# Generated by Django 3.1 on 2020-08-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0002_auto_20200819_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oss.telescope'),
        ),
    ]
