# Generated by Django 3.1 on 2020-08-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0003_instrument_telescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystatus',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oss.instrument'),
        ),
        migrations.AddField(
            model_name='facilitystatus',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oss.telescope'),
        ),
    ]
