# Generated by Django 3.1 on 2020-08-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0004_auto_20200819_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitystatus',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Status'),
        ),
    ]
