# Generated by Django 3.1 on 2020-08-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0005_facilitystatus_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oss.facilityoperator'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Site code'),
        ),
    ]
