# Generated by Django 3.1 on 2020-08-20 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0006_auto_20200820_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitystatus',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.instrument'),
        ),
        migrations.AlterField(
            model_name='facilitystatus',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oss.telescope'),
        ),
    ]
