# Generated by Django 3.1 on 2020-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0007_auto_20200820_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='tel_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telescope code'),
        ),
    ]
