# Generated by Django 3.1 on 2020-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0010_auto_20200825_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitystatus',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed-weather', 'Closed - weather'), ('Closed-unsafe-to-observe', 'Closed - site conditions unsafe for observations'), ('Closed-daytime', 'Closed - outside operational period'), ('Offline', 'Offline - engineering'), ('Unknown', 'Unknown or unrecognised status')], max_length=50, verbose_name='Status'),
        ),
    ]
