# Generated by Django 3.1 on 2020-08-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0011_auto_20200828_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='operator',
        ),
    ]
