# Generated by Django 3.1 on 2020-08-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0013_auto_20200831_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacilityOperator',
        ),
    ]
