# Generated by Django 3.1 on 2020-09-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0014_delete_facilityoperator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='wavelength',
            field=models.CharField(blank=True, choices=[('Optical', 'Optical'), ('IR', 'Infrared'), ('Millimeter', 'Millimeter'), ('Microwave', 'Microwave'), ('Radio', 'Radio'), ('UV', 'UV'), ('Gamma ray', 'Gamma ray'), ('X-ray', 'X-ray'), ('Gravitational waves', 'Gravitational waves'), ('Neutrinos', 'Neutrinos')], default='Optical', max_length=30, null=True, verbose_name='Wavelength range/messenger'),
        ),
        migrations.AlterField(
            model_name='site',
            name='orbit',
            field=models.CharField(blank=True, choices=[('Earth orbit', 'Earth orbit'), ('L2', 'L2'), ('Earth-trailing', 'Earth-trailing'), ('Equatorial Earth orbit', 'Equatorial Earth orbit'), ('LEO', 'Low Earth orbit'), ('Mars orbit', 'Mars orbit'), ('Outbound trajectory', 'Outbound trajectory')], max_length=30, null=True, verbose_name='Orbit'),
        ),
    ]
