# Generated by Django 3.1 on 2020-10-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss', '0017_auto_20201007_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='wavelength',
            field=models.CharField(blank=True, choices=[('Optical', 'Optical'), ('IR', 'Infrared'), ('Optical/NIR', 'Optical/Infrared'), ('UV/Optical/NIR', 'UV/Optical/Infrared'), ('Submillimeter', 'Submillimeter'), ('Millimeter', 'Millimeter'), ('Microwave', 'Microwave'), ('Radio', 'Radio'), ('UV', 'UV'), ('Gamma ray', 'Gamma ray'), ('X-ray', 'X-ray'), ('Gravitational waves', 'Gravitational waves'), ('Neutrinos', 'Neutrinos'), ('Cosmic rays', 'Cosmic rays')], default='Optical', max_length=30, null=True, verbose_name='Wavelength range/messenger'),
        ),
    ]
